### ISSUE TITLE
create the python notebook for assignment 1 and successfully get our fork running on it

### ISSUE THREAD

**Issue by majorsylvie** [majorsylvie/netml-transactions#4]
the main deliverable for this project is the rewritten assignment

this issue will involve
- creating the jupyter notebook within our fork
- getting our version of NetML running on it successfully
  - this means being able to open up a small pcap, turn it into a dataframe, and see the DNS column

this once this basic functionality has finished, we can actually write the assignment 1 code in there with issue #5

**Comment by Yuehan-Wang** [comment]
Got it running, able to print out dns_transaction_id column
<img width="970" alt="image" src="https://github.com/majorsylvie/netml-transactions/assets/62973650/723204ee-ff09-4861-b442-d64e46047e84">
